export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const PARTY_CREATE_START = "PARTY_CREATE_START";
export const PARTY_CREATE_SUCCESS = "PARTY_CREATE_SUCCESS";
export const PARTY_CREATE_FAIL = "PARTY_CREATE_FAIL";
export const PARTY_CREATE_FINISH = "PARTY_CREATE_FINISH";

export const PARTY_LEAVE_START = "PARTY_LEAVE_START";
export const PARTY_LEAVE_SUCCESS = "PARTY_LEAVE_SUCCESS";
export const PARTY_LEAVE_FAIL = "PARTY_LEAVE_FAIL";
export const PARTY_LEAVE_FINISH = "PARTY_LEAVE_FINISH";

export const PARTY_LIST_SUCCESS = "PARTY_LIST_SUCCESS";
export const PARTY_LIST_FAIL = "PARTY_LIST_FAIL";

export const PARTY_JOIN_START = "PARTY_JOIN_START";
export const PARTY_JOIN_SUCCESS = "PARTY_JOIN_SUCCESS";
export const PARTY_JOIN_FAIL = "PARTY_JOIN_FAIL";

export const SET_SOCKET = "SET_SOCKET";
export const PLAYER_JOINED_PARTY = "PLAYER_JOINED_PARTY";
export const PLAYER_LEFT_PARTY = "PLAYER_LEFT_PARTY";
export const PLAYER_DISBANDED_PARTY = "PLAYER_DISBANDED_PARTY";

export const GET_MAP_DATA = "GET_MAP_DATA";
export const SET_MAP_DATA_ON_LEADER_ENTER = "SET_MAP_DATA_ON_LEADER_ENTER";

export const REDIRECTED_TO_BATTLEFIELD = "REDIRECTED_TO_BATTLEFIELD";
export const PLAYER_ENTERED_BATTLEFIELD = "PLAYER_ENTERED_BATTLEFIELD";

export const PLAYER_LEFT_BATTLEFIELD = "PLAYER_LEFT_BATTLEFIELD";
export const ACTOR_MOVED_IN_BATTLEFIELD = "ACTOR_MOVED_IN_BATTLEFIELD";
